# Root output directory
# Individual eval runs will be saved as:
#
#   output_root/{name_prefix}/{dataset}__{model}__{representation}__{classifier}
output_root: output
name_prefix: eval_probe

# Remote root for backing up results
# currently only S3 supported
remote_root: null

# Description of the run. Goes in wandb notes.
notes: null

# Model and dataset extra kwargs
model_kwargs: {}
dataset_kwargs: {}

# Classifier settings

classifier_kwargs:
  # Intermediate embed dim for attn and mlp classifiers
  # Defaults to input embed dim
  embed_dim: null
  # Dropout for mlp classifier
  dropout: 0.0
  # Xavier initialization for linear classifier
  xavier_init: true
  # Batch norm for linear classifier
  norm: true

# Grid of learning rate and weight decay scale factors for classifier grid.
# Updated to dense lr grid and single wd grid since lr has much larger effect.
# [f"{lr:.2g}" for lr in np.logspace(-1.7, 1.7, 49)]
lr_scale_grid: [0.02, 0.023, 0.028, 0.033, 0.038, 0.045, 0.053, 0.062, 0.074, 0.087, 0.1, 0.12, 0.14, 0.17, 0.2, 0.23, 0.27, 0.32, 0.38, 0.44, 0.52, 0.61, 0.72, 0.85, 1, 1.2, 1.4, 1.6, 1.9, 2.3, 2.7, 3.1, 3.7, 4.3, 5.1, 6, 7.1, 8.3, 9.8, 12, 14, 16, 19, 22, 26, 31, 36, 43, 50]
#lr_scale_grid: [0.1, 0.2, 0.5, 1.0, 2.0, 5.0]
wd_scale_grid: [1.0]

# Data loader
num_workers: 8
prefetch_factor: null
# oversample minority classes for balanced sampling
balanced_sampling: true

# Optimization
# 4k steps over 20 short epochs to help with early stopping and plotting
epochs: 20
steps_per_epoch: 200
# total_batch_size = batch_size * accum_iter
batch_size: 16
accum_iter: 2

# base lr before lr scale
lr: 3e-4
# linear warmup
warmup_epochs: 5
# cosine decay by default
no_decay: false
# base wd before wd scale
weight_decay: 0.05
clip_grad: 1.0

# scoring metrics
metrics:
- acc
- f1
- auc

# any of the metrics, or neg_loss
# assumes higher is better
cv_metric: auc

# evaluate best checkpoint wrt to cv score
early_stopping: true

amp: true

device: cuda

seed: 4466
debug: false

wandb: false
wandb_entity: null
wandb_project: brainmarks
